//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cart
    {
        [Key]
        
        public int RecordId { get; set; }
        [DisplayName("品名")]
        public int Id { get; set; }

        [Required(AllowEmptyStrings = true, ErrorMessage = " ")]  //空白可以不顯示錯誤訊息 又可以不讓使用者輸空白
        [Range(0, 100, ErrorMessage = "數量必須為 0 ~ 100")]
        [DisplayName("數量")]
        public int Count { get; set; }

        public int Price { get; set; }

        public string OrderId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Item SaveItem { get; set; }

        [DisplayName("會員")]
        public string Account { get; set; }
       
        public string Name { get; set; }

        public virtual Item Item { get; set; }
    }
}
